{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-security-test",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-security-test",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-test-4.0.3.jar",
          "url": "spring-boot-starter-security-test-4.0.3.jar",
          "size": 4746,
          "sha512": "11bd8046f7585a3e4c1e84a5002fb441fba08152d427e7da10c2c0d9acb7ed69fe7a5466fbdb61f00c725894f6b0f1b6e0f593da36d596220559812b5356d372",
          "sha256": "075bb511bb9adc337f3be80c2747acafb34fa46adced02d539b90fdeed962b6a",
          "sha1": "d6ca39e10e6e972fd00d024d16deaaae16b22e4d",
          "md5": "1ef9495db232cd6a4f513d67cec79682"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-security-test",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-test-4.0.3.jar",
          "url": "spring-boot-starter-security-test-4.0.3.jar",
          "size": 4746,
          "sha512": "11bd8046f7585a3e4c1e84a5002fb441fba08152d427e7da10c2c0d9acb7ed69fe7a5466fbdb61f00c725894f6b0f1b6e0f593da36d596220559812b5356d372",
          "sha256": "075bb511bb9adc337f3be80c2747acafb34fa46adced02d539b90fdeed962b6a",
          "sha1": "d6ca39e10e6e972fd00d024d16deaaae16b22e4d",
          "md5": "1ef9495db232cd6a4f513d67cec79682"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-test-4.0.3-javadoc.jar",
          "url": "spring-boot-starter-security-test-4.0.3-javadoc.jar",
          "size": 4746,
          "sha512": "11bd8046f7585a3e4c1e84a5002fb441fba08152d427e7da10c2c0d9acb7ed69fe7a5466fbdb61f00c725894f6b0f1b6e0f593da36d596220559812b5356d372",
          "sha256": "075bb511bb9adc337f3be80c2747acafb34fa46adced02d539b90fdeed962b6a",
          "sha1": "d6ca39e10e6e972fd00d024d16deaaae16b22e4d",
          "md5": "1ef9495db232cd6a4f513d67cec79682"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-test-4.0.3-sources.jar",
          "url": "spring-boot-starter-security-test-4.0.3-sources.jar",
          "size": 4746,
          "sha512": "11bd8046f7585a3e4c1e84a5002fb441fba08152d427e7da10c2c0d9acb7ed69fe7a5466fbdb61f00c725894f6b0f1b6e0f593da36d596220559812b5356d372",
          "sha256": "075bb511bb9adc337f3be80c2747acafb34fa46adced02d539b90fdeed962b6a",
          "sha1": "d6ca39e10e6e972fd00d024d16deaaae16b22e4d",
          "md5": "1ef9495db232cd6a4f513d67cec79682"
        }
      ]
    }
  ]
}
