{
  "formatVersion": "1.1",
  "component": {
    "group": "com.structurizr",
    "module": "structurizr-export",
    "version": "5.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.structurizr",
          "module": "structurizr-core",
          "version": {
            "requires": "5.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "structurizr-export-5.0.3.jar",
          "url": "structurizr-export-5.0.3.jar",
          "size": 96957,
          "sha512": "3f1efdc36584606d192b2df194f6db5898e337fd5779771ef78ceabf4207180efb3a6a7989f8eca99f862ca4180ff89b84e3152d8896767ed9ffd046002efd3d",
          "sha256": "32075f8fb083ea37ef77b7bf44558948ffdd26fa7cea5009dc37e11d290aebad",
          "sha1": "c6a3ddeda5da312d05c5d4ec0640fb0e04ab3f6a",
          "md5": "290388ebf10ade2e07ca3fbc2425710a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.structurizr",
          "module": "structurizr-core",
          "version": {
            "requires": "5.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "structurizr-export-5.0.3.jar",
          "url": "structurizr-export-5.0.3.jar",
          "size": 96957,
          "sha512": "3f1efdc36584606d192b2df194f6db5898e337fd5779771ef78ceabf4207180efb3a6a7989f8eca99f862ca4180ff89b84e3152d8896767ed9ffd046002efd3d",
          "sha256": "32075f8fb083ea37ef77b7bf44558948ffdd26fa7cea5009dc37e11d290aebad",
          "sha1": "c6a3ddeda5da312d05c5d4ec0640fb0e04ab3f6a",
          "md5": "290388ebf10ade2e07ca3fbc2425710a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "structurizr-export-5.0.3-javadoc.jar",
          "url": "structurizr-export-5.0.3-javadoc.jar",
          "size": 174502,
          "sha512": "1be31b5d7c77a6678fad19123536e1c476c85408f18dd675788ff1fbad8d5852ac3f88beafd0caafee1de4db2367dca42c968fc269b5e3d0fe3f72b0ee61a40b",
          "sha256": "61afa0f8cf5b083c97a5c161fecf63b4bf7b9e0eb37cd5ace4243dd7c7542f26",
          "sha1": "4fba2ac4322de0022d18ba9091aa970c249f279f",
          "md5": "6a98c93278d621f2b093c6bc90979eda"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "structurizr-export-5.0.3-sources.jar",
          "url": "structurizr-export-5.0.3-sources.jar",
          "size": 43570,
          "sha512": "3543b843fed0e969c43274bb08397d5e5f4a634f7a3d9aab71a0e38c210256a2df5ba268263fb5fe4ca2ceb6ec1645774a221615569e37479afe466c85f9ce9f",
          "sha256": "ad825add5c433878c6db093996f4e87d9c2306b345d683650e7127e6f3830224",
          "sha1": "78758d401789c311b7c580011f5aea6dd0a7fa6a",
          "md5": "8caed24829c47922054e9233c7210606"
        }
      ]
    }
  ]
}
