{
  "formatVersion": "1.1",
  "component": {
    "group": "com.structurizr",
    "module": "structurizr-core",
    "version": "5.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.20"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "structurizr-core-5.0.3.jar",
          "url": "structurizr-core-5.0.3.jar",
          "size": 196174,
          "sha512": "0ec0877174c2905aff8f82518c086701ec7a499ecb84d007a72293d26426c73ba528a0f7500420c431617ba800ce3fb80132d02cc3d95c0a6969d7a2ff0f0d93",
          "sha256": "4c5035574797af60b93c1ba9005c2bfe53114dc287a475479bd98eb3e1331a62",
          "sha1": "a7dc28111d49939a2d4e8a947cddf9134d7d524a",
          "md5": "9b6a2d164f7768ccb3e112122b211b02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.20"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "structurizr-core-5.0.3.jar",
          "url": "structurizr-core-5.0.3.jar",
          "size": 196174,
          "sha512": "0ec0877174c2905aff8f82518c086701ec7a499ecb84d007a72293d26426c73ba528a0f7500420c431617ba800ce3fb80132d02cc3d95c0a6969d7a2ff0f0d93",
          "sha256": "4c5035574797af60b93c1ba9005c2bfe53114dc287a475479bd98eb3e1331a62",
          "sha1": "a7dc28111d49939a2d4e8a947cddf9134d7d524a",
          "md5": "9b6a2d164f7768ccb3e112122b211b02"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "structurizr-core-5.0.3-javadoc.jar",
          "url": "structurizr-core-5.0.3-javadoc.jar",
          "size": 508814,
          "sha512": "1ff79edc952fb461afbc7a87297b8b4dc583beb2089a7581343a8b95b2b57261e44c8fdc7a1c92ee9ca2c16d582c9dc74d0b869860d208ce5f006e619d0348ac",
          "sha256": "26441ea175cb79d4d0cbfe698cae23dd21ec40101ce5c3426f89b2656306cbcf",
          "sha1": "8888a3e1975d8433d05d36b7a2f8cfaba8ca40e2",
          "md5": "f65e6125e5d2abda2a28eaf991c7109d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "structurizr-core-5.0.3-sources.jar",
          "url": "structurizr-core-5.0.3-sources.jar",
          "size": 112312,
          "sha512": "18725c0972a319d5fb4ffe7de30d0d0388afa1237674a1944cdad26860ded6e11ea262e38456cb09b5c431180b20397dc2a27f510cab7e18e45bac1cb397311f",
          "sha256": "9d6f20e4f70f8352e9af20147c19649c5b1f91953c9130025139fe288827954f",
          "sha1": "7f4b2d3716663615065b06eb14d3ca78d6040f0f",
          "md5": "558b69512ef3da93aa429b2ff27c0dd7"
        }
      ]
    }
  ]
}
