{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-test",
    "version": "7.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-test-7.0.5.jar",
          "url": "spring-test-7.0.5.jar",
          "size": 1106275,
          "sha512": "6d4d4e02da57a17172bf52df7717538725024eb950c428ea80a40bbc1a35c30f77b35fd3d1659da589862945051978889b410fa1c878caf22a31a6f0c5eee970",
          "sha256": "235eed315b44c92b544f39db02716745e96ab5f454a1807a7a8614deee63e749",
          "sha1": "6a2783805884f8649a14459cc26f0c7222d4b9bd",
          "md5": "3ae75e72d28ffea1bb2e282805f30f29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-test-7.0.5.jar",
          "url": "spring-test-7.0.5.jar",
          "size": 1106275,
          "sha512": "6d4d4e02da57a17172bf52df7717538725024eb950c428ea80a40bbc1a35c30f77b35fd3d1659da589862945051978889b410fa1c878caf22a31a6f0c5eee970",
          "sha256": "235eed315b44c92b544f39db02716745e96ab5f454a1807a7a8614deee63e749",
          "sha1": "6a2783805884f8649a14459cc26f0c7222d4b9bd",
          "md5": "3ae75e72d28ffea1bb2e282805f30f29"
        }
      ]
    }
  ]
}
