{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-data-redis",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-data-commons",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-transaction",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.8.2.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-redis",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-data-redis-4.0.3.jar",
          "url": "spring-boot-data-redis-4.0.3.jar",
          "size": 82958,
          "sha512": "3fc60d38842fcbe78aef9e8d36b9cd0daff9f8855dde7c641dc53346e611b71f7ec38d261af0e0f4c560540615c3c27c61887ce4f08bd77b8811a6791e159175",
          "sha256": "f0646ffcf4ab3134b33cab79bb4945aba1b2c4ae2e8558e62d98cf50cd785390",
          "sha1": "41bade8fee87ab3ea84de718ba60d487f056f77b",
          "md5": "a245036b4f55c7842c40b60114197298"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-netty",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-data-commons",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-transaction",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.8.2.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-redis",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-data-redis-4.0.3.jar",
          "url": "spring-boot-data-redis-4.0.3.jar",
          "size": 82958,
          "sha512": "3fc60d38842fcbe78aef9e8d36b9cd0daff9f8855dde7c641dc53346e611b71f7ec38d261af0e0f4c560540615c3c27c61887ce4f08bd77b8811a6791e159175",
          "sha256": "f0646ffcf4ab3134b33cab79bb4945aba1b2c4ae2e8558e62d98cf50cd785390",
          "sha1": "41bade8fee87ab3ea84de718ba60d487f056f77b",
          "md5": "a245036b4f55c7842c40b60114197298"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-data-redis-4.0.3-javadoc.jar",
          "url": "spring-boot-data-redis-4.0.3-javadoc.jar",
          "size": 210842,
          "sha512": "fdf131dc0403d91edb27525609ea7cfa5339345353e815e3156c47bc188016756d195194cdf88b19201b7235a1a1fcf96447fd43352e8de416dd3a746ef48b30",
          "sha256": "55050ac1c456e206516d9ac7c2dd1fe5469080ea7ffe5b60d3f83569a65cb8d4",
          "sha1": "723cd7b50ac2e046d6ef55708ce5d21f3e784b89",
          "md5": "2b3bf53a0e2ee38d713ae29d6c0b2eb0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-data-redis-4.0.3-sources.jar",
          "url": "spring-boot-data-redis-4.0.3-sources.jar",
          "size": 49173,
          "sha512": "297518b5417bb7e41985c96b6253e76d8fbb7fe7114a2b571cac00063a235a86cabb1306e2b08127b78544b036203c1c8943bbb5444238d87952814c3eba11f8",
          "sha256": "ea6feefa7a0e9726d0fc3b7cf11b7eecdd74cc75f35aef33c2e2039564a2a8b3",
          "sha1": "e015b312e0eaae239ee29075aa2430c7918e5b8b",
          "md5": "7e9e28b9cae40945299b5a9df7fc829f"
        }
      ]
    }
  ]
}
