{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.datatype",
    "module": "jackson-datatype-jsr310",
    "version": "2.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.20"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.20.2.jar",
          "url": "jackson-datatype-jsr310-2.20.2.jar",
          "size": 137151,
          "sha512": "25acc7e7f4ab11eafa25e6d60304106ceb926c21e2e262498667c1955d2c6fe19f98f124c70ecc98a2b4909fe5b411aedc6c5ae6321c93c33c2f8a6db8bb4a8b",
          "sha256": "ff595a3cf009a25670c92d2f6939e3ffed4cdb37cba0d04f619e7ed43ce8ba1b",
          "sha1": "bbc60368883d441467f334ac4a0e974738698a7e",
          "md5": "558f4e661c97d61c259ee6e890a53fd4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.20"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.20.2.jar",
          "url": "jackson-datatype-jsr310-2.20.2.jar",
          "size": 137151,
          "sha512": "25acc7e7f4ab11eafa25e6d60304106ceb926c21e2e262498667c1955d2c6fe19f98f124c70ecc98a2b4909fe5b411aedc6c5ae6321c93c33c2f8a6db8bb4a8b",
          "sha256": "ff595a3cf009a25670c92d2f6939e3ffed4cdb37cba0d04f619e7ed43ce8ba1b",
          "sha1": "bbc60368883d441467f334ac4a0e974738698a7e",
          "md5": "558f4e661c97d61c259ee6e890a53fd4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.20.2-javadoc.jar",
          "url": "jackson-datatype-jsr310-2.20.2-javadoc.jar",
          "size": 447914,
          "sha512": "f3cc047d2aa1cd533dbcb59d69184c33c311a321adbcc1bacc244bf1775477fb94c0d2c66a2d3bd88173322060e7d5965aaabf066d7453afa0d70373621f676c",
          "sha256": "983994ef1b4fb3c51124100af6013dca6d001a9c4403ecfb8ead986c9fed53fd",
          "sha1": "d1df3272415f69d16feae14359626621c1364f24",
          "md5": "9cc4401d5898e0ad2da556cb99719f32"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.20.2-sources.jar",
          "url": "jackson-datatype-jsr310-2.20.2-sources.jar",
          "size": 92928,
          "sha512": "0ccd84748e3877544c7bddc3fad9f25d9ef5e4a453df59abd00077a5e9813592dd4e9b9df83d03c439bbcc0f4d403867a46c54907697736c34aaf27c52846529",
          "sha256": "758bfb24c6ad89b5129caf7762cc4044ed2dc1c1e36e8af48bbae532fecaefd3",
          "sha1": "776c0ce8614ffe04cdbe7aec4c0022c61721dc3b",
          "md5": "be77ce2f05ae86b5cfe3bd78e50b5d73"
        }
      ]
    }
  ]
}
