{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry",
    "module": "opentelemetry-sdk-metrics",
    "version": "1.55.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.55.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-common",
          "version": {
            "requires": "1.55.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-sdk-metrics-1.55.0.jar",
          "url": "opentelemetry-sdk-metrics-1.55.0.jar",
          "size": 328364,
          "sha512": "97ec6a268b0e141bc5e8a3337430c85a84fdfe01bc2853d1706c788ecb2c45b9188d6c6e18c46eea251f6ad9f37426893c759751d2e1cbb10091313be9819654",
          "sha256": "6219d69c3abdd6113bee35df94826f48e84b742041f5124b5857a2b801f74573",
          "sha1": "2db32c617c5d37c9ee69d58009edcc9a12ba6a24",
          "md5": "3a1985ee03d33b6251bf10dbd5174d98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.55.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-common",
          "version": {
            "requires": "1.55.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-sdk-metrics-1.55.0.jar",
          "url": "opentelemetry-sdk-metrics-1.55.0.jar",
          "size": 328364,
          "sha512": "97ec6a268b0e141bc5e8a3337430c85a84fdfe01bc2853d1706c788ecb2c45b9188d6c6e18c46eea251f6ad9f37426893c759751d2e1cbb10091313be9819654",
          "sha256": "6219d69c3abdd6113bee35df94826f48e84b742041f5124b5857a2b801f74573",
          "sha1": "2db32c617c5d37c9ee69d58009edcc9a12ba6a24",
          "md5": "3a1985ee03d33b6251bf10dbd5174d98"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-sdk-metrics-1.55.0-javadoc.jar",
          "url": "opentelemetry-sdk-metrics-1.55.0-javadoc.jar",
          "size": 217248,
          "sha512": "dc3aa0802ee2a0b7fd8da7a52d8ac7ea342bd8544ca4ef4606d84163c6acf1690eae7a36364d6ab4849888d8c72456d8f9fb998b9dcb39b985bfec6a671b6289",
          "sha256": "d4c4803989c1340e34bd6f0ef3f5d950872a9c71a8fb21146d93307da841b702",
          "sha1": "6b2eb7937114e990767f334664104a74eda58366",
          "md5": "26567865ff5608a4f835a560cedca97b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-sdk-metrics-1.55.0-sources.jar",
          "url": "opentelemetry-sdk-metrics-1.55.0-sources.jar",
          "size": 180715,
          "sha512": "27582f1191cb44a735ab94c84bc444b16481f388d23f0fffbccc65f21388dda7811f81d13414364a534904962734d8325bc18324efbfc0ec70076f5672be5e4c",
          "sha256": "5f9c8dab78339e402caa7f7aa4616b6b5c8e2d50201335c73e23bd21aba147fd",
          "sha1": "7fe6da05b8966856c5c1b7650c273e396cddb429",
          "md5": "4a923a98a305d7b3f692149feffe02ad"
        }
      ]
    }
  ]
}
