{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-actuator",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-micrometer-metrics",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-health",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-jakarta9",
          "version": {
            "requires": "1.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-4.0.3.jar",
          "url": "spring-boot-starter-actuator-4.0.3.jar",
          "size": 4805,
          "sha512": "d7685df3c050bf6a2c1dccd234ca871b0ceeb1f1068f346ce7bf82ddcc16f484b27b5da0e713236ad5b01426bed0d5679b91796cb30647f00d6cbed3de004b19",
          "sha256": "a4f727e57f62c3cc093c1c78b8261c1090276b52467732a0133c2dc9279c02a0",
          "sha1": "0a3a1f12b8096b30e8b3d6971cd907a089503302",
          "md5": "a13731cc0ffc35bb40bef04ff504b4da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-micrometer-metrics",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-health",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-jakarta9",
          "version": {
            "requires": "1.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-4.0.3.jar",
          "url": "spring-boot-starter-actuator-4.0.3.jar",
          "size": 4805,
          "sha512": "d7685df3c050bf6a2c1dccd234ca871b0ceeb1f1068f346ce7bf82ddcc16f484b27b5da0e713236ad5b01426bed0d5679b91796cb30647f00d6cbed3de004b19",
          "sha256": "a4f727e57f62c3cc093c1c78b8261c1090276b52467732a0133c2dc9279c02a0",
          "sha1": "0a3a1f12b8096b30e8b3d6971cd907a089503302",
          "md5": "a13731cc0ffc35bb40bef04ff504b4da"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-4.0.3-javadoc.jar",
          "url": "spring-boot-starter-actuator-4.0.3-javadoc.jar",
          "size": 4805,
          "sha512": "d7685df3c050bf6a2c1dccd234ca871b0ceeb1f1068f346ce7bf82ddcc16f484b27b5da0e713236ad5b01426bed0d5679b91796cb30647f00d6cbed3de004b19",
          "sha256": "a4f727e57f62c3cc093c1c78b8261c1090276b52467732a0133c2dc9279c02a0",
          "sha1": "0a3a1f12b8096b30e8b3d6971cd907a089503302",
          "md5": "a13731cc0ffc35bb40bef04ff504b4da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-4.0.3-sources.jar",
          "url": "spring-boot-starter-actuator-4.0.3-sources.jar",
          "size": 4805,
          "sha512": "d7685df3c050bf6a2c1dccd234ca871b0ceeb1f1068f346ce7bf82ddcc16f484b27b5da0e713236ad5b01426bed0d5679b91796cb30647f00d6cbed3de004b19",
          "sha256": "a4f727e57f62c3cc093c1c78b8261c1090276b52467732a0133c2dc9279c02a0",
          "sha1": "0a3a1f12b8096b30e8b3d6971cd907a089503302",
          "md5": "a13731cc0ffc35bb40bef04ff504b4da"
        }
      ]
    }
  ]
}
