{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test-autoconfigure",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-4.0.3.jar",
          "url": "spring-boot-test-autoconfigure-4.0.3.jar",
          "size": 27877,
          "sha512": "761221144b649f832321c61a14999207755e8e51af2a2df3fd6200da2f223fb9c69741595ad5b52ee568ebfc1c6fa78101d0d1e75959edf4790c6045fc89d664",
          "sha256": "5bf5f5c39d66cd9e09b8e08e768c3a197b6c08426525442f50913c4adea57317",
          "sha1": "7b867b1caa522f85dbaa7d5f4e107ed62695fe5c",
          "md5": "ff441c1afed872af25bbb80b139ac22c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-4.0.3.jar",
          "url": "spring-boot-test-autoconfigure-4.0.3.jar",
          "size": 27877,
          "sha512": "761221144b649f832321c61a14999207755e8e51af2a2df3fd6200da2f223fb9c69741595ad5b52ee568ebfc1c6fa78101d0d1e75959edf4790c6045fc89d664",
          "sha256": "5bf5f5c39d66cd9e09b8e08e768c3a197b6c08426525442f50913c4adea57317",
          "sha1": "7b867b1caa522f85dbaa7d5f4e107ed62695fe5c",
          "md5": "ff441c1afed872af25bbb80b139ac22c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-4.0.3-javadoc.jar",
          "url": "spring-boot-test-autoconfigure-4.0.3-javadoc.jar",
          "size": 141832,
          "sha512": "8973026a10068824048644b6465cc2f0f40edb3ac4ead58043043c114446489216439711d74b2e20a4c2564be756a73e2ebee32ee3d2066634180939911bff27",
          "sha256": "e76ca1321f3bbd491501551b368f04a8c851248709fc911097ecb1faa73ca561",
          "sha1": "305fda4087c528e228841b20add7514e8a371c8f",
          "md5": "b42ea639d51191017ac629165db91f99"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-4.0.3-sources.jar",
          "url": "spring-boot-test-autoconfigure-4.0.3-sources.jar",
          "size": 25255,
          "sha512": "06ff8b822adb9a38dc4fcb108f568c4b19bfac7b7ed84273553896c68c6feb4dfb31a8d585d0366c617014754ec1e3eedb783861964a6af385541f968e632a15",
          "sha256": "1ed8b0b63237ea16b494610b52ab2ff2c1fc022f5b3079091e70deb4347bed11",
          "sha1": "f9e7d1d7c9a14ad58c528a9a8545b17e5d9df08c",
          "md5": "203afcee048831e37f0e7d0b474ab22f"
        }
      ]
    }
  ]
}
