{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okhttp/5.2.1/okhttp-5.2.1.module",
    "group": "com.squareup.okhttp3",
    "module": "okhttp",
    "version": "5.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-jvm-5.2.1.jar",
          "url": "okhttp-jvm-5.2.1.jar",
          "size": 871211,
          "sha512": "be95cc3875323dc3191ee282e5a39c4e93d22aa6ae8b597577b8d410346a79e6f55fb14cf970f1fff18bda3afc5227670fb6b764e6ed49a7282be71bfc6902ab",
          "sha256": "9632c08567dbb21c569b13d793107834c8580d44e4eea74b2eae0722f0506179",
          "sha1": "239374c8de427f72657c0145dda769fccb17a7b2",
          "md5": "213b755dac4db34f967ffd2583100adb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-jvm-5.2.1.jar",
          "url": "okhttp-jvm-5.2.1.jar",
          "size": 871211,
          "sha512": "be95cc3875323dc3191ee282e5a39c4e93d22aa6ae8b597577b8d410346a79e6f55fb14cf970f1fff18bda3afc5227670fb6b764e6ed49a7282be71bfc6902ab",
          "sha256": "9632c08567dbb21c569b13d793107834c8580d44e4eea74b2eae0722f0506179",
          "sha1": "239374c8de427f72657c0145dda769fccb17a7b2",
          "md5": "213b755dac4db34f967ffd2583100adb"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "okhttp-jvm-5.2.1-sources.jar",
          "url": "okhttp-jvm-5.2.1-sources.jar",
          "size": 397696,
          "sha512": "df0087d16090df84d2a9b299ffbd2e11a43297d63b27efe2fa27b91220b5bfe0c97e1839670519115b5a405fc79be64ffae4a7246713fb68b098eaaf9b20335f",
          "sha256": "9fa32be62c7a46ffe70cdb1bf7e195f5ee3fc885999379292cb636b5aa311704",
          "sha1": "c332a37c2139217341efc8e79f37072e33476e79",
          "md5": "c9af79fff6771401431b8a72bc4f20d1"
        }
      ]
    }
  ]
}
