{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry.proto",
    "module": "opentelemetry-proto",
    "version": "1.8.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.32.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-proto-1.8.0-alpha.jar",
          "url": "opentelemetry-proto-1.8.0-alpha.jar",
          "size": 906059,
          "sha512": "d808286d80eb16e5769a491f0659ac09562ba99358fb261edc789b3a62bc53fe0edc74ae8f41572ad60d9d14e64f189d17c3c714b8b522a36848cb0195f90107",
          "sha256": "c551873983e22b308c738860da0903cdff2e47182140cf2a8dd9abb1adf31d08",
          "sha1": "02b40108f65cbbbc142c1abf9f4a0599c968434a",
          "md5": "c8e327173e239341d9c9274a16c811c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.32.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-proto-1.8.0-alpha.jar",
          "url": "opentelemetry-proto-1.8.0-alpha.jar",
          "size": 906059,
          "sha512": "d808286d80eb16e5769a491f0659ac09562ba99358fb261edc789b3a62bc53fe0edc74ae8f41572ad60d9d14e64f189d17c3c714b8b522a36848cb0195f90107",
          "sha256": "c551873983e22b308c738860da0903cdff2e47182140cf2a8dd9abb1adf31d08",
          "sha1": "02b40108f65cbbbc142c1abf9f4a0599c968434a",
          "md5": "c8e327173e239341d9c9274a16c811c3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-proto-1.8.0-alpha-javadoc.jar",
          "url": "opentelemetry-proto-1.8.0-alpha-javadoc.jar",
          "size": 1390078,
          "sha512": "3b9eabf6f8ecf7d61567840670590082ca47e56a8cc249cb5235f4fc3df87f87c341111178a261bf78b8c5910d46432cf9708f2438183d27fe8b96af92c88135",
          "sha256": "c42a7a5ba87178073c1326f53f11ac50fc458c319fe91d2fb913476be2f7b0a5",
          "sha1": "0d2860d86fa3c7aabdedaa27a5d7bd1a1a9aeecc",
          "md5": "a4bbe534502848dd22de6ca12381e6cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-proto-1.8.0-alpha-sources.jar",
          "url": "opentelemetry-proto-1.8.0-alpha-sources.jar",
          "size": 441822,
          "sha512": "ec3bb602f7935da65bc2c74d177a2d3ba9a562e09d4919c3949c66f027338c7e462109874c6a5c06273fddad69433bd4ca172ce3cef400f972d52e2801b7226f",
          "sha256": "a416e1bc4bb2246cc0b56169287999db29f14d68b27957b7a27a1d69068e2b55",
          "sha1": "8d387c80de441a72f950b3b8c62a74a5e97bcc26",
          "md5": "3b2bf6d2b09eddd31b026f555ec9cec3"
        }
      ]
    }
  ]
}
