{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-opentelemetry",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-micrometer-metrics",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-micrometer-tracing-opentelemetry",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-opentelemetry",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-opentelemetry-4.0.3.jar",
          "url": "spring-boot-starter-opentelemetry-4.0.3.jar",
          "size": 4745,
          "sha512": "43262fe54059d21252f534f42d667f86c94852a40f0fb5ee5e0ee1ee43a107095b0c6423d96229e4fb8e0b5490591f4e40ac9eac1f46444a1f567064c876163b",
          "sha256": "594970ae8902368e8b0dc733b414f54d06c37df416ab9b8c8e667f36185430eb",
          "sha1": "03c261e4b47c567f74826382af4c5c962b7b1b6d",
          "md5": "a128ec44cef278bccd37e31da7720129"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-micrometer-metrics",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-micrometer-tracing-opentelemetry",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-opentelemetry",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-registry-otlp",
          "version": {
            "requires": "1.16.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-tracing-bridge-otel",
          "version": {
            "requires": "1.6.3"
          },
          "excludes": [
            {
              "group": "aopalliance",
              "module": "aopalliance"
            }
          ]
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.55.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-opentelemetry-4.0.3.jar",
          "url": "spring-boot-starter-opentelemetry-4.0.3.jar",
          "size": 4745,
          "sha512": "43262fe54059d21252f534f42d667f86c94852a40f0fb5ee5e0ee1ee43a107095b0c6423d96229e4fb8e0b5490591f4e40ac9eac1f46444a1f567064c876163b",
          "sha256": "594970ae8902368e8b0dc733b414f54d06c37df416ab9b8c8e667f36185430eb",
          "sha1": "03c261e4b47c567f74826382af4c5c962b7b1b6d",
          "md5": "a128ec44cef278bccd37e31da7720129"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-opentelemetry-4.0.3-javadoc.jar",
          "url": "spring-boot-starter-opentelemetry-4.0.3-javadoc.jar",
          "size": 4745,
          "sha512": "43262fe54059d21252f534f42d667f86c94852a40f0fb5ee5e0ee1ee43a107095b0c6423d96229e4fb8e0b5490591f4e40ac9eac1f46444a1f567064c876163b",
          "sha256": "594970ae8902368e8b0dc733b414f54d06c37df416ab9b8c8e667f36185430eb",
          "sha1": "03c261e4b47c567f74826382af4c5c962b7b1b6d",
          "md5": "a128ec44cef278bccd37e31da7720129"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-opentelemetry-4.0.3-sources.jar",
          "url": "spring-boot-starter-opentelemetry-4.0.3-sources.jar",
          "size": 4745,
          "sha512": "43262fe54059d21252f534f42d667f86c94852a40f0fb5ee5e0ee1ee43a107095b0c6423d96229e4fb8e0b5490591f4e40ac9eac1f46444a1f567064c876163b",
          "sha256": "594970ae8902368e8b0dc733b414f54d06c37df416ab9b8c8e667f36185430eb",
          "sha1": "03c261e4b47c567f74826382af4c5c962b7b1b6d",
          "md5": "a128ec44cef278bccd37e31da7720129"
        }
      ]
    }
  ]
}
