{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry",
    "module": "opentelemetry-exporter-otlp-common",
    "version": "1.55.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-common",
          "version": {
            "requires": "1.55.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-exporter-otlp-common-1.55.0.jar",
          "url": "opentelemetry-exporter-otlp-common-1.55.0.jar",
          "size": 222895,
          "sha512": "bb21d75dcaa22fa2ad63ee3360453123cb5d19f04cc3d0f699a5444f02782bcbf727e892a03391c45ab348bc6366a3f2d43e4311925d534d9b4332d98886113e",
          "sha256": "7ddfa417d88a5ff8626dad9ebe0c8c59776491478ab1f72aedfacd75b984931f",
          "sha1": "b26d3a697e4d42fa12e61e5e9c6dfacb46250766",
          "md5": "32fe425d421e825f89de149631062818"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-common",
          "version": {
            "requires": "1.55.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-exporter-otlp-common-1.55.0.jar",
          "url": "opentelemetry-exporter-otlp-common-1.55.0.jar",
          "size": 222895,
          "sha512": "bb21d75dcaa22fa2ad63ee3360453123cb5d19f04cc3d0f699a5444f02782bcbf727e892a03391c45ab348bc6366a3f2d43e4311925d534d9b4332d98886113e",
          "sha256": "7ddfa417d88a5ff8626dad9ebe0c8c59776491478ab1f72aedfacd75b984931f",
          "sha1": "b26d3a697e4d42fa12e61e5e9c6dfacb46250766",
          "md5": "32fe425d421e825f89de149631062818"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-exporter-otlp-common-1.55.0-javadoc.jar",
          "url": "opentelemetry-exporter-otlp-common-1.55.0-javadoc.jar",
          "size": 375,
          "sha512": "2d5b06550f6c481c6de2a4a478708c993bd8005137734637481f87812f95d03ef9bd56fbcd56c381cc6f8ab70057a78dda300030cea8f716df82feaebe743872",
          "sha256": "08ffb9ebf304e1d3a8a8b79309bff63dd6491cb14727caa3fa92429aaabec47c",
          "sha1": "6f7eca532a6698f7f0759a6ffa1a4f3a7f88836b",
          "md5": "de9701d24ab613bb146284c00cb83282"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-exporter-otlp-common-1.55.0-sources.jar",
          "url": "opentelemetry-exporter-otlp-common-1.55.0-sources.jar",
          "size": 122340,
          "sha512": "02fa015727960a58fa34d4555a46bbd80e0442120ec0c2b0a7815c457ae052f420b4b896d22a43a0b05cbef07cdf7e661a274869e7fd56f610326a204426cf29",
          "sha256": "7b36e1080bbb2c4dbc7ce009393c568e3d968328f0e5891beb1e45ebd894337a",
          "sha1": "a01ea4202916b290865f9844116d4155f581cfd7",
          "md5": "c3db81e600a7870f9c01606541d9a294"
        }
      ]
    }
  ]
}
