{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio/3.16.1/okio-3.16.1.module",
    "group": "com.squareup.okio",
    "module": "okio",
    "version": "3.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-3.16.1.jar",
          "url": "okio-jvm-3.16.1.jar",
          "size": 382776,
          "sha512": "6a9f40e35279f6b810c5cfe7a586437ca38198c8b2445c5c0f1f92da47b7ba09b8cb49bda5c869327250e7721ba3bb35a11326e76faac964a564d55c4d525a02",
          "sha256": "31f48e6463ec587d6d262d042c91da00659c983b6ad20d5982bf31e85222693c",
          "sha1": "2c8e9a56ce1a1b30ec920fb93a3a9980cf34b015",
          "md5": "91861b97b10e5588199f57c52462f1e3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-3.16.1.jar",
          "url": "okio-jvm-3.16.1.jar",
          "size": 382776,
          "sha512": "6a9f40e35279f6b810c5cfe7a586437ca38198c8b2445c5c0f1f92da47b7ba09b8cb49bda5c869327250e7721ba3bb35a11326e76faac964a564d55c4d525a02",
          "sha256": "31f48e6463ec587d6d262d042c91da00659c983b6ad20d5982bf31e85222693c",
          "sha1": "2c8e9a56ce1a1b30ec920fb93a3a9980cf34b015",
          "md5": "91861b97b10e5588199f57c52462f1e3"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "okio-jvm-3.16.1-sources.jar",
          "url": "okio-jvm-3.16.1-sources.jar",
          "size": 190096,
          "sha512": "3ea274cdf5e641850773d58fd9f03defe9e333679647856bb4c751a0ff644c227d60bb91a4ee1dfd963dcfcf4d422a1dd2f94fbc7b2fc4b3ffcb9c81b41e3454",
          "sha256": "b29b5f4ad1adfd7cbfb3d388f7bf29d1702f0b85be1b6c61b0185ce7e2b2e6dc",
          "sha1": "73deb884027a514f4ff0bc0304e3879b4df5fb3a",
          "md5": "a37eb89949dc8aeb6e76ad15e4158a16"
        }
      ]
    }
  ]
}
