{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-micrometer-metrics",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-micrometer-metrics",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-micrometer-metrics-4.0.3.jar",
          "url": "spring-boot-starter-micrometer-metrics-4.0.3.jar",
          "size": 4748,
          "sha512": "6db042390855279f5acb40c64ec8db0af7e581dddfc222cea9d05e076f40d39b0a8cefd65ca3d0af4abc3835034d20777688e05165445c082c7808738bd4e057",
          "sha256": "1ba79bdf8d165d3e57e5280f73f92d5a9b06e254988ef191e25822c82ee6013c",
          "sha1": "371cb699b09c40aecbbacee2abdbcdc84044ec39",
          "md5": "120e61d91d6eb62f3b3135cd41d904ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-micrometer-metrics",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-micrometer-metrics-4.0.3.jar",
          "url": "spring-boot-starter-micrometer-metrics-4.0.3.jar",
          "size": 4748,
          "sha512": "6db042390855279f5acb40c64ec8db0af7e581dddfc222cea9d05e076f40d39b0a8cefd65ca3d0af4abc3835034d20777688e05165445c082c7808738bd4e057",
          "sha256": "1ba79bdf8d165d3e57e5280f73f92d5a9b06e254988ef191e25822c82ee6013c",
          "sha1": "371cb699b09c40aecbbacee2abdbcdc84044ec39",
          "md5": "120e61d91d6eb62f3b3135cd41d904ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-micrometer-metrics-4.0.3-javadoc.jar",
          "url": "spring-boot-starter-micrometer-metrics-4.0.3-javadoc.jar",
          "size": 4748,
          "sha512": "6db042390855279f5acb40c64ec8db0af7e581dddfc222cea9d05e076f40d39b0a8cefd65ca3d0af4abc3835034d20777688e05165445c082c7808738bd4e057",
          "sha256": "1ba79bdf8d165d3e57e5280f73f92d5a9b06e254988ef191e25822c82ee6013c",
          "sha1": "371cb699b09c40aecbbacee2abdbcdc84044ec39",
          "md5": "120e61d91d6eb62f3b3135cd41d904ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-micrometer-metrics-4.0.3-sources.jar",
          "url": "spring-boot-starter-micrometer-metrics-4.0.3-sources.jar",
          "size": 4748,
          "sha512": "6db042390855279f5acb40c64ec8db0af7e581dddfc222cea9d05e076f40d39b0a8cefd65ca3d0af4abc3835034d20777688e05165445c082c7808738bd4e057",
          "sha256": "1ba79bdf8d165d3e57e5280f73f92d5a9b06e254988ef191e25822c82ee6013c",
          "sha1": "371cb699b09c40aecbbacee2abdbcdc84044ec39",
          "md5": "120e61d91d6eb62f3b3135cd41d904ac"
        }
      ]
    }
  ]
}
