package com.acme.jitsi.shared;

public enum ErrorCode {
  // Security / cross-cutting
  AUTH_REQUIRED("AUTH_REQUIRED"),
  ACCESS_DENIED("ACCESS_DENIED"),
  TENANT_CLAIM_REQUIRED("TENANT_CLAIM_REQUIRED"),
  TENANT_ACCESS_DENIED("TENANT_ACCESS_DENIED"),
  INVALID_REQUEST("INVALID_REQUEST"),
  INVALID_ROLE("INVALID_ROLE"),
  PROFILE_VALIDATION_FAILED("PROFILE_VALIDATION_FAILED"),
  INVALID_INVITE("INVALID_INVITE"),
  INVALID_PERSISTED_STATE("INVALID_PERSISTED_STATE"),
  INTERNAL_ERROR("INTERNAL_ERROR"),

  // Meetings domain
  MEETING_NOT_FOUND("MEETING_NOT_FOUND"),
  INVALID_SCHEDULE("INVALID_SCHEDULE"),
  VALIDATION_ERROR("VALIDATION_ERROR"),
  MEETING_FINALIZED("MEETING_FINALIZED"),
  ROOM_INACTIVE("ROOM_INACTIVE"),
  ASSIGNMENT_NOT_FOUND("ASSIGNMENT_NOT_FOUND"),
  INVITE_NOT_FOUND("INVITE_NOT_FOUND"),
  INVITE_ALREADY_REVOKED("INVITE_ALREADY_REVOKED"),
  INVITE_EXPIRED("INVITE_EXPIRED"),
  INVITE_EXHAUSTED("INVITE_EXHAUSTED"),
  INVITE_REVOKED("INVITE_REVOKED"),
  BULK_INVITE_VALIDATION_FAILED("BULK_INVITE_VALIDATION_FAILED"),
  INVALID_RECIPIENT_FORMAT("INVALID_RECIPIENT_FORMAT"),
  MEETING_CANCELED("MEETING_CANCELED"),
  MEETING_ENDED("MEETING_ENDED"),
  MEETING_ROLE_CONFLICT("MEETING_ROLE_CONFLICT"),
  ROLE_CONFLICT("ROLE_CONFLICT"),
  ROLE_MISMATCH("ROLE_MISMATCH"),
  ROOM_CLOSED("ROOM_CLOSED"),

  // Rooms domain
  ROOM_NOT_FOUND("ROOM_NOT_FOUND"),
  ROOM_NAME_CONFLICT("ROOM_NAME_CONFLICT"),
  ROOM_HAS_ACTIVE_MEETINGS("ROOM_HAS_ACTIVE_MEETINGS"),
  ROOM_ALREADY_CLOSED("ROOM_ALREADY_CLOSED"),

  // ConfigSets domain
  CONFIG_SET_INVALID("CONFIG_SET_INVALID"),
  CONFIG_SET_NOT_FOUND("CONFIG_SET_NOT_FOUND"),
  CONFIG_SET_NAME_CONFLICT("CONFIG_SET_NAME_CONFLICT"),
  CONFIG_SET_ACTIVATION_NOT_ALLOWED("CONFIG_SET_ACTIVATION_NOT_ALLOWED"),
  CONFIG_SET_ROLLOUT_NOT_ALLOWED("CONFIG_SET_ROLLOUT_NOT_ALLOWED"),
  CONFIG_INCOMPATIBLE("CONFIG_INCOMPATIBLE"),
  CONFIG_SET_ROLLBACK_NOT_ALLOWED("CONFIG_SET_ROLLBACK_NOT_ALLOWED"),

  // Profiles domain
  PROFILE_NOT_FOUND("PROFILE_NOT_FOUND"),

  // Auth domain
  TOKEN_INVALID("TOKEN_INVALID"),
  TOKEN_REVOKED("TOKEN_REVOKED"),
  REFRESH_REUSE_DETECTED("REFRESH_REUSE_DETECTED"),

  // Infrastructure
  IDEMPOTENCY_CONFLICT("IDEMPOTENCY_CONFLICT"),
  IDEMPOTENCY_KEY_INVALID("IDEMPOTENCY_KEY_INVALID");

  private final String code;

  ErrorCode(String code) {
    this.code = code;
  }

  public String code() {
    return code;
  }
}