server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: lax

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  openapi:
    server-url: ${APP_OPENAPI_SERVER_URL:https://mgorka-conf.top}
