{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-test",
    "version": "7.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "7.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-test-7.0.3.jar",
          "url": "spring-security-test-7.0.3.jar",
          "size": 142966,
          "sha512": "2c58760f9a4cd0e3857538bd113cb797163684af873ef1d23ad80fd2529a45a1d3bdd31a657b4a5ccfc9dcb615d4134357f753ea3a84ad5e84b3dd9ba0e10832",
          "sha256": "82aa636a14aa065f17ee5d83885f3b1c6f5da84a717ec762012b930cece2ab6c",
          "sha1": "70e376562c093a9be57ae42a9e89fa7586a6666a",
          "md5": "6c9420979012959865cae0b4fa6daf5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "7.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-test-7.0.3.jar",
          "url": "spring-security-test-7.0.3.jar",
          "size": 142966,
          "sha512": "2c58760f9a4cd0e3857538bd113cb797163684af873ef1d23ad80fd2529a45a1d3bdd31a657b4a5ccfc9dcb615d4134357f753ea3a84ad5e84b3dd9ba0e10832",
          "sha256": "82aa636a14aa065f17ee5d83885f3b1c6f5da84a717ec762012b930cece2ab6c",
          "sha1": "70e376562c093a9be57ae42a9e89fa7586a6666a",
          "md5": "6c9420979012959865cae0b4fa6daf5a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-test-7.0.3-javadoc.jar",
          "url": "spring-security-test-7.0.3-javadoc.jar",
          "size": 238718,
          "sha512": "eca3aa3e9b4635ea0a0152a3bd43025b262bb6982e7494f4ce4f1497a0424c4b7dc9e88e0ac02577589855d30222418cbd361de34c062bdf9c1b16a8f66e3458",
          "sha256": "d7d490574e89934a9bfe39d71ff65ea1cbd17e746895bf707235aa291b9a26a2",
          "sha1": "e29195a2398e462b43b9aafb3b47f0cd80bfef6c",
          "md5": "7ab9d856b188be974dc0a91e69995848"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-test-7.0.3-sources.jar",
          "url": "spring-security-test-7.0.3-sources.jar",
          "size": 67898,
          "sha512": "c040efc066d7f3f6aedf3e53ff0a3c1425b1fe20ef341636cf224bda2fc5021680ef0431e3f6f356c15454ad50615ebdc5d3c143d03236a8eb6f64f763752a12",
          "sha256": "7adcfb970b0788a3ec89907c44d71f78cc53986ee1b90931e46e2be56d57f8c2",
          "sha1": "67e3e34c683a33cc2f54700048890b063a5e12fb",
          "md5": "42ca37850e7642d827ff13343b28fb65"
        }
      ]
    }
  ]
}
