{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-oauth2-core",
    "version": "7.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-oauth2-core-7.0.3.jar",
          "url": "spring-security-oauth2-core-7.0.3.jar",
          "size": 114075,
          "sha512": "aba8303f38346fcd93e3214664eef3fb60c3e3a41c625736139bff3b00cf470c15df0c1311612ad16f28ea588433768c3c03f2888fe1ce99777ffc4398b2aec1",
          "sha256": "9f88d6fa4fdab63177560b40a33bf5ccd2d2b8e5d47195759c0aadca9f73806a",
          "sha1": "e381cffca3e4a935c2ae0053899f1f404fd0b129",
          "md5": "27a99099df882af3a406463b2d00a97d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-oauth2-core-7.0.3.jar",
          "url": "spring-security-oauth2-core-7.0.3.jar",
          "size": 114075,
          "sha512": "aba8303f38346fcd93e3214664eef3fb60c3e3a41c625736139bff3b00cf470c15df0c1311612ad16f28ea588433768c3c03f2888fe1ce99777ffc4398b2aec1",
          "sha256": "9f88d6fa4fdab63177560b40a33bf5ccd2d2b8e5d47195759c0aadca9f73806a",
          "sha1": "e381cffca3e4a935c2ae0053899f1f404fd0b129",
          "md5": "27a99099df882af3a406463b2d00a97d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-oauth2-core-7.0.3-javadoc.jar",
          "url": "spring-security-oauth2-core-7.0.3-javadoc.jar",
          "size": 366388,
          "sha512": "010c2f5826fbe8366045ae38c75739b85682c078f0d0dd7e634a79c6cee9ecd3c5369eaf216eafcbc31572e533812c6051c0337fd829d2e905445e5db612be05",
          "sha256": "b9b17ab5c9932d98479c1f617e3e818e97d2a2f12d5d1cfeb60d210c4636f330",
          "sha1": "9de675bfd187b36d983719d79c74ffab2d1239da",
          "md5": "4fabd59000448b6fdc7aa84af20b3799"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-oauth2-core-7.0.3-sources.jar",
          "url": "spring-security-oauth2-core-7.0.3-sources.jar",
          "size": 106005,
          "sha512": "a85260aa3c9e956c4a6076887e841f8fee1a80e28c4e47d23f70311a5eeffd27db4d35ae0dff6f9e9a766f883006445c4f0b9a571ae175d98d5624456a5bd889",
          "sha256": "323057bc6a914153746742927b2c1d168beab5116c61f7bbff05035ba66a46cb",
          "sha1": "573e76dcd0b392285424eab4629bcf3408e1796a",
          "md5": "dc0994d9181988bfc3817e20acf296e4"
        }
      ]
    }
  ]
}
