{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-redis",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-data-redis",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-redis-4.0.3.jar",
          "url": "spring-boot-starter-data-redis-4.0.3.jar",
          "size": 4784,
          "sha512": "d18406617d17fbbadaae26100d2579851cc266d17f6badfc0dadfd89401fb640b06f7e77cb303782632d3ac33a4406d46ed21c12da4fab34eb43aa5c05333a4c",
          "sha256": "2974e17bbe99a6c0fb0fa00f1167c7dc87271f8f9ed11632567e7b41c9748ae6",
          "sha1": "6bd0ea1d29b6e282f22ada9b37a014ff8a224c39",
          "md5": "485aeed2cf1ccc5fd855de8a14da08d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-data-redis",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-redis-4.0.3.jar",
          "url": "spring-boot-starter-data-redis-4.0.3.jar",
          "size": 4784,
          "sha512": "d18406617d17fbbadaae26100d2579851cc266d17f6badfc0dadfd89401fb640b06f7e77cb303782632d3ac33a4406d46ed21c12da4fab34eb43aa5c05333a4c",
          "sha256": "2974e17bbe99a6c0fb0fa00f1167c7dc87271f8f9ed11632567e7b41c9748ae6",
          "sha1": "6bd0ea1d29b6e282f22ada9b37a014ff8a224c39",
          "md5": "485aeed2cf1ccc5fd855de8a14da08d8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-4.0.3-javadoc.jar",
          "url": "spring-boot-starter-data-redis-4.0.3-javadoc.jar",
          "size": 4784,
          "sha512": "d18406617d17fbbadaae26100d2579851cc266d17f6badfc0dadfd89401fb640b06f7e77cb303782632d3ac33a4406d46ed21c12da4fab34eb43aa5c05333a4c",
          "sha256": "2974e17bbe99a6c0fb0fa00f1167c7dc87271f8f9ed11632567e7b41c9748ae6",
          "sha1": "6bd0ea1d29b6e282f22ada9b37a014ff8a224c39",
          "md5": "485aeed2cf1ccc5fd855de8a14da08d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-4.0.3-sources.jar",
          "url": "spring-boot-starter-data-redis-4.0.3-sources.jar",
          "size": 4784,
          "sha512": "d18406617d17fbbadaae26100d2579851cc266d17f6badfc0dadfd89401fb640b06f7e77cb303782632d3ac33a4406d46ed21c12da4fab34eb43aa5c05333a4c",
          "sha256": "2974e17bbe99a6c0fb0fa00f1167c7dc87271f8f9ed11632567e7b41c9748ae6",
          "sha1": "6bd0ea1d29b6e282f22ada9b37a014ff8a224c39",
          "md5": "485aeed2cf1ccc5fd855de8a14da08d8"
        }
      ]
    }
  ]
}
