package com.acme.jitsi.infrastructure.idempotency;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.*;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.Callable;
import java.util.concurrent.Executors;
import org.aspectj.lang.ProceedingJoinPoint;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.dao.DataAccessResourceFailureException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

class IdempotencyAspectTest {
    private JdbcTemplate jdbc;
    private IdempotencyAspect aspect;
    private ProceedingJoinPoint call;
    private Idempotent policy;
    private MockHttpServletRequest request;

    @BeforeEach
    void setUp() throws Exception {
        var source = new DriverManagerDataSource("jdbc:h2:mem:" + UUID.randomUUID()
                + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        jdbc = spy(new JdbcTemplate(source));
        jdbc.execute(Files.readString(Path.of("src/main/resources/db/migration/V25__Transactional_idempotency.sql")));
        jdbc.execute("CREATE TABLE effects (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
        aspect = new IdempotencyAspect(jdbc, new DataSourceTransactionManager(source), Duration.ofHours(24), 128);
        call = mock(ProceedingJoinPoint.class);
        policy = getClass().getDeclaredMethod("ordinaryOperation").getAnnotation(Idempotent.class);
        request = request("same-key");
        RequestContextHolder.setRequestAttributes(new ServletRequestAttributes(request));
    }

    @AfterEach
    void resetContext() {
        RequestContextHolder.resetRequestAttributes();
        SecurityContextHolder.clearContext();
    }

    @Idempotent
    private void ordinaryOperation() { }

    @Idempotent(noRollbackFor = IllegalArgumentException.class)
    private void recordedFailure() { }

    @Test
    void effectAndMarkerCommitTogetherAndRejectAllDuplicatePayloads() throws Throwable {
        when(call.proceed()).thenAnswer(ignored -> jdbc.update("INSERT INTO effects DEFAULT VALUES"));
        assertThat(aspect.handleIdempotency(call, policy)).isEqualTo(1);
        request.setContent("changed payload".getBytes(java.nio.charset.StandardCharsets.UTF_8));
        assertThatThrownBy(() -> aspect.handleIdempotency(call, policy)).isInstanceOf(IdempotencyConflictException.class);
        assertThat(count("effects")).isEqualTo(1);
        assertThat(count("idempotency_requests")).isEqualTo(1);
        verify(call).proceed();
    }

    @Test
    void failureAfterTheMutationRollsBackBothEffectAndMarkerAndAllowsRetry() throws Throwable {
        when(call.proceed()).thenAnswer(ignored -> {
            jdbc.update("INSERT INTO effects DEFAULT VALUES");
            throw new IllegalStateException("response construction failed");
        });
        assertThatThrownBy(() -> aspect.handleIdempotency(call, policy)).isInstanceOf(IllegalStateException.class);
        assertThat(count("effects")).isZero();
        assertThat(count("idempotency_requests")).isZero();
        doReturn("retry succeeded").when(call).proceed();
        assertThat(aspect.handleIdempotency(call, policy)).isEqualTo("retry succeeded");
    }

    @Test
    void failureWritingCompletionCannotLeaveAnUnmarkedDatabaseEffect() throws Throwable {
        when(call.proceed()).thenAnswer(ignored -> jdbc.update("INSERT INTO effects DEFAULT VALUES"));
        doThrow(new DataAccessResourceFailureException("completion write failed"))
                .when(jdbc).update(eq("UPDATE idempotency_requests SET expires_at = ? WHERE request_key = ?"), any(Object[].class));
        assertThatThrownBy(() -> aspect.handleIdempotency(call, policy)).isInstanceOf(DataAccessResourceFailureException.class);
        assertThat(count("effects")).isZero();
        assertThat(count("idempotency_requests")).isZero();
    }

    @Test
    void deliberateRecordedFailureCommitsItsHistoryAndDuplicateGuard() throws Throwable {
        policy = getClass().getDeclaredMethod("recordedFailure").getAnnotation(Idempotent.class);
        when(call.proceed()).thenAnswer(ignored -> {
            jdbc.update("INSERT INTO effects DEFAULT VALUES");
            throw new IllegalArgumentException("validation history must be retained");
        });
        assertThatThrownBy(() -> aspect.handleIdempotency(call, policy)).isInstanceOf(IllegalArgumentException.class);
        assertThat(count("effects")).isEqualTo(1);
        assertThatThrownBy(() -> aspect.handleIdempotency(call, policy)).isInstanceOf(IdempotencyConflictException.class);
    }

    @Test
    void declaredRecordedFailurePreservesOriginalExceptionWhenNestedTransactionAlreadyRolledBack() throws Throwable {
        policy = getClass().getDeclaredMethod("recordedFailure").getAnnotation(Idempotent.class);
        var nested = new org.springframework.transaction.support.TransactionTemplate(
                new DataSourceTransactionManager(jdbc.getDataSource()));
        when(call.proceed()).thenAnswer(ignored -> nested.execute(status -> {
            jdbc.update("INSERT INTO effects DEFAULT VALUES");
            throw new IllegalArgumentException("rejected before partial result");
        }));
        assertThatThrownBy(() -> aspect.handleIdempotency(call, policy))
                .isInstanceOf(IllegalArgumentException.class).hasMessage("rejected before partial result");
        assertThat(count("effects")).isZero();
        assertThat(count("idempotency_requests")).isZero();
    }

    @Test
    void keysAreScopedBySubjectMethodAndObservedUri() throws Throwable {
        when(call.proceed()).thenReturn("ok");
        authenticate("alice");
        aspect.handleIdempotency(call, policy);
        authenticate("bob");
        aspect.handleIdempotency(call, policy);
        request.setMethod("PUT");
        aspect.handleIdempotency(call, policy);
        request.setRequestURI("/other");
        aspect.handleIdempotency(call, policy);
        assertThat(count("idempotency_requests")).isEqualTo(4);
    }

    @Test
    void concurrentDuplicateHasOnlyOneDatabaseEffect() throws Throwable {
        when(call.proceed()).thenAnswer(ignored -> jdbc.update("INSERT INTO effects DEFAULT VALUES"));
        Callable<Boolean> attempt = () -> {
            RequestContextHolder.setRequestAttributes(new ServletRequestAttributes(request("concurrent")));
            try {
                aspect.handleIdempotency(call, policy);
                return true;
            } catch (IdempotencyConflictException duplicate) {
                return false;
            } catch (Throwable exception) {
                throw new AssertionError(exception);
            } finally {
                RequestContextHolder.resetRequestAttributes();
            }
        };
        try (var executor = Executors.newFixedThreadPool(2)) {
            var results = executor.invokeAll(List.of(attempt, attempt));
            assertThat(results.get(0).get() ^ results.get(1).get()).isTrue();
        }
        assertThat(count("effects")).isEqualTo(1);
    }

    @Test
    void expiredMarkersAreReclaimedButActiveMarkersStay() throws Throwable {
        when(call.proceed()).thenReturn("ok");
        aspect.handleIdempotency(call, policy);
        aspect.removeExpiredMarkers();
        assertThat(count("idempotency_requests")).isEqualTo(1);
        jdbc.update("UPDATE idempotency_requests SET expires_at = TIMESTAMP '2000-01-01 00:00:00'");
        aspect.removeExpiredMarkers();
        assertThat(count("idempotency_requests")).isZero();
        assertThat(aspect.handleIdempotency(call, policy)).isEqualTo("ok");
    }

    @Test
    void missingKeyOrNonHttpInvocationDoesNotCreateMarker() throws Throwable {
        when(call.proceed()).thenReturn("ok");
        request.removeHeader("Idempotency-Key");
        aspect.handleIdempotency(call, policy);
        RequestContextHolder.resetRequestAttributes();
        aspect.handleIdempotency(call, policy);
        assertThat(count("idempotency_requests")).isZero();
    }

    @Test
    void invalidKeysNeverInvokeTheOperation() {
        request = request("a".repeat(129));
        RequestContextHolder.setRequestAttributes(new ServletRequestAttributes(request));
        assertThatThrownBy(() -> aspect.handleIdempotency(call, policy)).isInstanceOf(InvalidIdempotencyKeyException.class);
        request.removeHeader("Idempotency-Key");
        request.addHeader("Idempotency-Key", "bad key");
        assertThatThrownBy(() -> aspect.handleIdempotency(call, policy)).isInstanceOf(InvalidIdempotencyKeyException.class);
        verifyNoInteractions(call);
    }

    private int count(String table) {
        return jdbc.queryForObject("SELECT COUNT(*) FROM " + table, Integer.class);
    }

    private static MockHttpServletRequest request(String key) {
        var request = new MockHttpServletRequest("POST", "/api/v1/test/idempotent");
        request.addHeader("Idempotency-Key", key);
        return request;
    }

    private static void authenticate(String subject) {
        SecurityContextHolder.getContext().setAuthentication(
                UsernamePasswordAuthenticationToken.authenticated(subject, "", List.of()));
    }
}
