{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-micrometer-metrics",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-micrometer-observation",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-micrometer-metrics-4.0.3.jar",
          "url": "spring-boot-micrometer-metrics-4.0.3.jar",
          "size": 240648,
          "sha512": "3d45812cb8c43ec3966f81d0e16a2849cbff3c75c862c4f55a5ebd12ffde2bd35aff910b77bfae54eeb66b92ac4e56b4b3804194c6633fa64284fff6a4dd029e",
          "sha256": "de26013c6e2327e77937b1cb71de07f204048d8d16e3184f241b513339c7a2d6",
          "sha1": "71e3082be1b56777f93f6d2c11b5754469c45f0f",
          "md5": "7ed461a6be287bc228e979c096b88f38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-micrometer-observation",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-micrometer-metrics-4.0.3.jar",
          "url": "spring-boot-micrometer-metrics-4.0.3.jar",
          "size": 240648,
          "sha512": "3d45812cb8c43ec3966f81d0e16a2849cbff3c75c862c4f55a5ebd12ffde2bd35aff910b77bfae54eeb66b92ac4e56b4b3804194c6633fa64284fff6a4dd029e",
          "sha256": "de26013c6e2327e77937b1cb71de07f204048d8d16e3184f241b513339c7a2d6",
          "sha1": "71e3082be1b56777f93f6d2c11b5754469c45f0f",
          "md5": "7ed461a6be287bc228e979c096b88f38"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-micrometer-metrics-4.0.3-javadoc.jar",
          "url": "spring-boot-micrometer-metrics-4.0.3-javadoc.jar",
          "size": 528613,
          "sha512": "2b8e22b1227ddaf18f9fdcf606c8f26ff36acfdea74e1c2fca8ae3aaa6a6a40551c787e9a4a8e4cf3733b128d0f18cdb52e4d5c9c836b794795375949dedf53a",
          "sha256": "a776d5ab82d73d72709642f830b321ec997062690614bce084cc1d30eb1e3f67",
          "sha1": "0f22ea12d79e4d732227b9bc019dbeb82d9bc967",
          "md5": "5badefc682d73b670d6925a7df5bb6ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-micrometer-metrics-4.0.3-sources.jar",
          "url": "spring-boot-micrometer-metrics-4.0.3-sources.jar",
          "size": 169009,
          "sha512": "5e410647c368bd781a8c59ece46a2b50001a66affa16d9830b70cc1ec2f6131f03af120e53159ef526c6ef1dd1036483bbe3466678a0e7fadcd24c9a6e335aee",
          "sha256": "bbe1aa8d41256b8aeb51f2edbc87d25380765b5c6a3d5b8e7ce3f4f4f2ce30a3",
          "sha1": "99debcbdfb9e5c86dd912e2f5bd740c906efb3b2",
          "md5": "f5fe16c3d25de861707c70825f5584b3"
        }
      ]
    }
  ]
}
