set $portal_return_url "https://jitsi-mgorka.top";

location = / {
    return 302 $portal_return_url;
}

location = /static/close.html {
    return 302 $portal_return_url;
}

location = /static/close2.html {
    return 302 $portal_return_url;
}
